# enter to ipython

 1.introduce the numpy and matplotlib
 #numpy is a library like matlab, matplotlib used to 2D plotting 

In [5]:
import numpy
from matplotlib import pyplot # a model used to plot

In [6]:
a = numpy.linspace(0.0, 10 ,20)
print(a)
#creates an array with equally spaced numbers between a start and end

[  0.           0.52631579   1.05263158   1.57894737   2.10526316
   2.63157895   3.15789474   3.68421053   4.21052632   4.73684211
   5.26315789   5.78947368   6.31578947   6.84210526   7.36842105
   7.89473684   8.42105263   8.94736842   9.47368421  10.        ]


In [7]:
import numpy as np
import matplotlib.pyplot as plt
#creat shortcut 

In [8]:
a = 5      # a is an integer 5
b = 'five' # b is a string of the word 'five'
c = 5.0    # c is a floating point 5

In [11]:
type(a)

int

In [12]:
type(b)

str

In [13]:
type(c)

float

loop

In [17]:
n = 10
c = 0
for i in range(n):
    c = c + 1
print(c)


10


In [20]:
n = 3
for i in range(n):
    for j in range(n):
        print(i, j)
    print("this is a beautiful dividing line")

0 0
0 1
0 2
this is a beautiful dividing line
1 0
1 1
1 2
this is a beautiful dividing line
2 0
2 1
2 2
this is a beautiful dividing line


Slicing arrays

In [21]:
arrays = numpy.array([1, 2, 3, 4, 5])
arrays

array([1, 2, 3, 4, 5])

In [23]:
brrays = [6, 7, 8, 9]
brrays

[6, 7, 8, 9]

In [26]:
n = 5 
for i in range(n):
    arrays[i]

In [29]:
arrays[0], arrays[3], arrays[4]

(1, 4, 5)

In [30]:
arrays[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [31]:
arrays[0:3] #grabbing a range of values

array([1, 2, 3])

Note here, the slice is inclusive on the front end and exclusive on the back, so the above command gives us the values of myvals[0], myvals[1] and myvals[2], but not myvals[3].

# Assigning array variables

In [35]:
a = numpy.linspace(1.0, 10.0, 10)
a

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [37]:
b = a
b

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [38]:
a[2] = 20 

In [42]:
a

array([  1.,   2.,  20.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [43]:
b

array([  1.,   2.,  20.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

When you use a statement like a = b, rather than copying all the values of a into a new array called b, Python just creates an alias called b and tells it to route us to a. So if we change a value in a, then b will reflect that change (technically, this is called assignment by reference). If you want to make a true copy of the array, you have to tell Python to create a copy of a.

In [48]:
c = a.copy() 
# that is how to make a true copy

In [46]:
a[3] = 5
a

array([  1.,   2.,  20.,   5.,   5.,   6.,   7.,   8.,   9.,  10.])

In [47]:
c

array([  1.,   2.,  20.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])